// 검사 스크립트의 테스트. 실행: node --test scripts/scripts.test.mjs
// 임시 폴더에 작은 프로젝트를 만들어 스크립트를 실제로 실행하고 종료 코드와 출력을 확인한다.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import {
  chmodSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, beforeEach, describe, it } from "node:test";
import { fileURLToPath } from "node:url";

const SCRIPTS = dirname(fileURLToPath(import.meta.url));
const DEV = { ref: "devrefdevrefdevrefde", name: "tool-dev" };
const PROD = { ref: "prodrefprodrefprodre", name: "tool-prod" };

let project = "";
const write = (path, content = "") => {
  const file = join(project, path);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  return file;
};
const run = (script, args = [], options = {}) =>
  spawnSync("node", [join(SCRIPTS, script), ...args], {
    cwd: project,
    encoding: "utf8",
    ...options,
    env: { ...process.env, ...options.env },
  });
const migration = (name, sql) => write(`supabase/migrations/${name}.sql`, sql);
const config = (extensions) =>
  write(
    "project.config.json",
    JSON.stringify({ extensions, db: { anonReadableTables: [] } }),
  );

beforeEach(() => {
  project = mkdtempSync(join(tmpdir(), "template-scripts-"));
  write("package.json", JSON.stringify({ name: "fixture", dependencies: {} }));
  config([]);
  migration(
    "20260101000000_rbac",
    `create function public.custom_access_token_hook(event jsonb) returns jsonb language sql as $$ select event $$;
     create function public.authorize(p text) returns boolean language sql as $$ select true $$;
     create table public.profiles (id uuid primary key);`,
  );
});
afterEach(() => rmSync(project, { recursive: true, force: true }));

describe("check-migrations", () => {
  const check = () => run("check-migrations.mjs");

  it("더하기만 하는 마이그레이션은 통과한다", () => {
    migration(
      "20260201000000_add_requests",
      `create table public.requests (id bigint generated by default as identity primary key, memo text);
       alter table public.requests enable row level security;
       alter table public.requests add column amount integer check (amount >= 0);
       alter table public.requests add column is_urgent boolean not null default false;
       comment on column public.requests.memo is '열을 지우는 방법: drop column 은 쓰지 않는다';
       -- drop table public.requests; 는 주석이라 검사하지 않는다`,
    );
    const result = check();
    assert.equal(result.status, 0, result.stderr);
  });
  it("잘못된 정책을 고치는 drop policy 는 통과한다", () => {
    migration(
      "20260201000000_fix_policy",
      `drop policy if exists "requests: read" on public.requests;`,
    );
    assert.equal(check().status, 0);
  });

  const destructive = {
    "테이블 삭제": "drop table public.profiles;",
    "열 삭제": "alter table public.profiles drop column full_name;",
    "타입 삭제": "drop type public.app_role;",
    "테이블 이름 변경": "alter table public.profiles rename to people;",
    "열 이름 변경":
      "alter table public.profiles rename column full_name to name;",
    "enum 값 이름 변경":
      "alter type public.app_role rename value 'member' to 'user';",
    "열의 종류 변경":
      "alter table public.profiles alter column full_name type varchar(10);",
    "전체 행 삭제": "truncate public.profiles;",
  };
  for (const [title, sql] of Object.entries(destructive)) {
    it(`${title}을(를) 막고 다음에 할 일을 알린다`, () => {
      migration("20260201000000_change", sql);
      const result = check();
      assert.equal(result.status, 1);
      assert.match(
        result.stderr,
        /supabase\/migrations\/20260201000000_change\.sql:1/,
      );
      assert.match(result.stderr, /다음: /);
    });
  }
  it("사유를 적은 마지막 제거 단계는 통과한다", () => {
    migration(
      "20260201000000_drop_old_column",
      `-- destructive-ok: 3단계. 코드가 new_name 만 읽는 것을 운영에서 2주 확인했다\nalter table public.profiles drop column old_name;`,
    );
    assert.equal(check().status, 0);
  });
  it("사유가 없거나 짧으면 막는다", () => {
    migration(
      "20260201000000_drop_old_column",
      `-- destructive-ok: ok\nalter table public.profiles drop column old_name;`,
    );
    assert.equal(check().status, 1);
  });
  it("사유를 적어도 RLS 끄기는 막는다", () => {
    migration(
      "20260201000000_disable",
      `-- destructive-ok: 빠르게 시험하려고 잠깐 끈다고 적어 본다\nalter table public.profiles disable row level security;`,
    );
    assert.match(check().stderr, /RLS 끄기/);
  });
  it("기본값 없는 not null 열을 막는다", () => {
    migration(
      "20260201000000_add",
      "alter table public.profiles add column team text not null;",
    );
    assert.match(check().stderr, /기본값이 없다/);
  });
  it("새 enum 값을 같은 파일에서 쓰면 막는다", () => {
    migration(
      "20260201000000_add_permission",
      `alter type public.app_permission add value 'requests.approve';
       insert into public.role_permissions (role, permission) values ('admin', 'requests.approve');`,
    );
    assert.match(check().stderr, /바로 쓴다/);
  });
  it("enum 값만 더하는 파일은 통과한다", () => {
    migration(
      "20260201000000_add_permission",
      "alter type public.app_permission add value 'requests.approve';",
    );
    assert.equal(check().status, 0);
  });
  it("파일 이름 형식을 확인한다", () => {
    migration("add_requests", "select 1;");
    assert.match(check().stderr, /파일 이름/);
  });
  const sensitive = {
    주민등록번호: "alter table public.profiles add column national_id_number text, add column nickname text;",
    "주민등록번호(create table)":
      "create table public.staff (id uuid primary key, name text not null, resident_registration_no varchar(14), check (char_length(name) > 0));",
    여권번호: 'alter table public.profiles add column if not exists "passport_no" text;',
    계좌번호: "create table public.payees (id uuid primary key, bank_account text);",
    카드번호: "alter table public.profiles add card_number text;",
  };
  for (const [kind, sql] of Object.entries(sensitive)) {
    it(`${kind} 열을 막는다`, () => {
      migration("20260201000000_add_column", sql);
      const result = check();
      assert.equal(result.status, 1);
      assert.match(result.stderr, new RegExp(kind.replace(/\(.*/, "")));
      assert.match(result.stderr, /sensitive-ok/);
    });
  }
  it("사유를 적은 sensitive-ok 가 있으면 통과한다", () => {
    migration(
      "20260201000000_add_column",
      "-- sensitive-ok: 급여 이체용. pgcrypto 로 암호화한 값만 넣기로 사용자가 정했다\nalter table public.profiles add column bank_account bytea;",
    );
    assert.equal(check().status, 0);
  });
  it("사유가 짧은 sensitive-ok 는 막는다", () => {
    migration(
      "20260201000000_add_column",
      "-- sensitive-ok: 필요\nalter table public.profiles add column bank_account bytea;",
    );
    assert.match(check().stderr, /사유가 너무 짧다/);
  });
  it("비슷한 이름의 보통 열과 제약은 막지 않는다", () => {
    migration(
      "20260201000000_add_column",
      `create table public.cards (id uuid primary key, card_title text, international_id_type text, account_id uuid, discount numeric(5, 2), constraint cards_title check (char_length(card_title) > 0));
       alter table public.cards add constraint cards_account unique (account_id);
       comment on column public.cards.card_title is '주민등록번호는 저장하지 않는다';`,
    );
    const result = check();
    assert.equal(result.status, 0, result.stderr);
  });
  it("연락처 열은 막지 않고 알리기만 한다", () => {
    migration(
      "20260201000000_add_column",
      "alter table public.profiles add column phone_number text;",
    );
    const result = check();
    assert.equal(result.status, 0, result.stderr);
    assert.match(result.stdout, /개인정보로 보이는 열을 더한다: public\.profiles\.phone_number/);
  });
  it("이미 DB 에 적용한 파일은 검사하지 않는다", () => {
    migration("20260201000000_old", "drop table public.legacy;");
    write("supabase/.pushed", "20260201000000_old.sql\n");
    assert.equal(check().status, 0);
  });
});

describe("check-extensions", () => {
  const check = () => run("check-extensions.mjs");
  const uses = {
    storage: () =>
      write(
        "app/(app)/files/actions.ts",
        `await supabase.storage.from("attachments").createSignedUploadUrl(path);`,
      ),
    email: () =>
      write("package.json", JSON.stringify({ dependencies: { resend: "^6" } })),
    excel: () =>
      write(
        "package.json",
        JSON.stringify({
          dependencies: {
            xlsx: "https://cdn.sheetjs.com/xlsx-0.20.3/xlsx-0.20.3.tgz",
          },
        }),
      ),
    "db-functions": () =>
      migration(
        "20260201000000_guard",
        "create function private.guard() returns trigger language plpgsql as $$ begin return new; end $$;",
      ),
    "scheduled-jobs": () =>
      write(
        "vercel.json",
        JSON.stringify({
          crons: [{ path: "/api/cron/expire", schedule: "0 0 * * *" }],
        }),
      ),
    "edge-functions": () =>
      write("supabase/functions/webhook/index.ts", "export default {};"),
    "admin-api": () =>
      write(
        "lib/supabase/admin.ts",
        `import "server-only";\nexport const key = process.env.SUPABASE_SECRET_KEY;`,
      ),
    "multi-org": () =>
      migration(
        "20260201000000_orgs",
        "create table public.documents (id bigint primary key, org_id uuid not null);",
      ),
    realtime: () =>
      write(
        "components/live-list.tsx",
        `"use client";\nsupabase.channel("requests").subscribe();`,
      ),
  };

  it("시작 상태는 통과한다", () => {
    const result = check();
    assert.equal(result.status, 0, result.stderr);
  });
  for (const [name, use] of Object.entries(uses)) {
    it(`${name}: 켜지 않고 쓰면 알리고, 켜면 같은 코드가 통과한다`, () => {
      use();
      const before = check();
      assert.equal(before.status, 1);
      assert.match(before.stderr, new RegExp(`다음: /add-extension ${name} `));

      config([name]);
      const after = check();
      assert.equal(after.status, 0, after.stderr);
    });
  }
  it("admin-api 를 켜도 다른 파일의 secret 키 사용은 막는다", () => {
    uses["admin-api"]();
    config(["admin-api"]);
    write(
      "app/(app)/admin/actions.ts",
      "const key = process.env.SUPABASE_SECRET_KEY;",
    );
    const result = check();
    assert.equal(result.status, 1);
    assert.match(result.stderr, /app\/\(app\)\/admin\/actions\.ts/);
  });
  it("admin-api 클라이언트에 server-only 가 없으면 막는다", () => {
    write(
      "lib/supabase/admin.ts",
      "export const key = process.env.SUPABASE_SECRET_KEY;",
    );
    config(["admin-api"]);
    assert.match(check().stderr, /server-only/);
  });
  it("브라우저에 노출되는 secret 변수 이름을 막는다", () => {
    write("lib/x.ts", "process.env.NEXT_PUBLIC_SUPABASE_SECRET_KEY");
    assert.match(check().stderr, /브라우저에 노출/);
  });
  it("클라이언트 컴포넌트가 서버 전용 클라이언트를 불러오면 막는다", () => {
    write(
      "components/list.tsx",
      `"use client";\nimport { createClient } from "@/lib/supabase/server";`,
    );
    assert.match(check().stderr, /클라이언트 컴포넌트/);
  });
  it("알 수 없는 확장 이름을 알린다", () => {
    config(["storge"]);
    assert.match(check().stderr, /알 수 없는 확장 이름: storge/);
  });
  it("테이블이 많아도 막지 않는다", () => {
    migration(
      "20260201000000_many",
      Array.from(
        { length: 30 },
        (_, index) => `create table public.t${index} (id bigint primary key);`,
      ).join("\n"),
    );
    assert.equal(check().status, 0);
  });
});

describe("check-app", () => {
  const check = () => run("check-app.mjs");
  const GOOD_ACTION = `"use server";
export async function save(_previous, formData) {
  const actor = await requireUser();
  const input = schema.safeParse({ name: formData.get("name") });
  return { ok: true };
}`;
  const good = () => {
    write(
      "app/(app)/memos/page.tsx",
      "export default async function Page() { await requireUser(); return null; }",
    );
    write(
      "app/(app)/memos/queries.ts",
      'import "server-only";\nexport async function list() { return []; }',
    );
    write("app/(app)/memos/actions.ts", GOOD_ACTION);
    write(
      "app/(app)/memos/rules.ts",
      'import type { Database } from "@/lib/supabase/database.types";\nexport function checkMemo(): string | null { return null; }',
    );
    write("app/(app)/memos/rules.test.ts", 'it("규칙", () => {});');
    write(
      "app/(app)/memos/memo-form.tsx",
      '"use client";\nimport type { Memo } from "./queries";\nexport function MemoForm() { return <p className="text-muted-foreground">메모</p>; }',
    );
    write(
      "app/(auth)/login/page.tsx",
      "export default function Login() { return null; }",
    );
    write(
      "app/(auth)/login/actions.ts",
      '"use server";\nexport async function login(_previous, formData) { const input = schema.safeParse({}); }',
    );
    write(
      "components/ui/badge.tsx",
      'export const Badge = () => <span className="bg-red-500" />;',
    );
  };

  it("규칙대로 쓴 화면은 통과한다", () => {
    good();
    const result = check();
    assert.equal(result.status, 0, result.stderr);
  });

  const bad = {
    "로그인을 확인하지 않는 페이지": [
      "app/(app)/memos/page.tsx",
      "export default async function Page() { const user = await getUser(); return null; }",
      /로그인을 확인하지 않는다/,
    ],
    "클라이언트 컴포넌트인 페이지": [
      "app/(app)/memos/page.tsx",
      '"use client";\nexport default function Page() { requireUser(); return null; }',
      /페이지가 클라이언트 컴포넌트/,
    ],
    "server-only 가 없는 조회": [
      "app/(app)/memos/queries.ts",
      "export async function list() { return []; }",
      /server-only/,
    ],
    "use server 가 없는 액션": [
      "app/(app)/memos/actions.ts",
      GOOD_ACTION.replace('"use server";', ""),
      /use server/,
    ],
    "로그인을 확인하지 않는 액션": [
      "app/(app)/memos/actions.ts",
      GOOD_ACTION.replace("const actor = await requireUser();", ""),
      /서버 액션 save 이 로그인을 확인하지 않는다/,
    ],
    "입력을 검증하지 않는 액션": [
      "app/(app)/memos/actions.ts",
      GOOD_ACTION.replace("schema.safeParse(", "parse("),
      /입력을 검증하지 않는다/,
    ],
    "내보내는 것이 없는 규칙 파일": [
      "app/(app)/memos/rules.ts",
      "// 규칙 없음",
      /내보내는 규칙이 없다/,
    ],
    "순수하지 않은 규칙 파일": [
      "app/(app)/memos/rules.ts",
      'import { createClient } from "@/lib/supabase/server";\nexport function checkMemo() { return null; }',
      /순수 함수/,
    ],
    "조회를 불러오는 클라이언트 컴포넌트": [
      "app/(app)/memos/memo-form.tsx",
      '"use client";\nimport { list } from "./queries";',
      /queries\.ts 를 불러온다/,
    ],
    "색을 직접 지정한 화면": [
      "app/(app)/memos/memo-form.tsx",
      '"use client";\nexport function MemoForm() { return <p className="border bg-orange-50 text-orange-900">메모</p>; }',
      /색을 직접 지정했다: bg-orange-50/,
    ],
    "색 값을 직접 적은 화면": [
      "features/memos/memo-card.tsx",
      'export function MemoCard() { return <p style={{ color: "red" }}>메모</p>; }',
      /직접 적었다/,
    ],
  };
  for (const [title, [path, content, expected]] of Object.entries(bad)) {
    it(`${title}을(를) 알린다`, () => {
      good();
      write(path, content);
      const result = check();
      assert.equal(result.status, 1);
      assert.match(result.stderr, expected);
      assert.match(result.stderr, /다음: /);
    });
  }
  const action = (body) => `"use server";
export async function approve(_previous, formData) {
  const actor = await requireUser();
  const input = schema.safeParse({ id: formData.get("id") });
${body}
  revalidatePath("/requests");
  return { ok: true };
}`;
  const UPDATE = `  const changed = await supabase.from("requests").update({ status: "approved", approver_id: actor.id })
    .eq("id", input.data.id).eq("status", current.data.status).select("id");`;
  const badActions = {
    "페이지용 권한 확인을 쓴 액션": [
      action(UPDATE).replace(
        "await requireUser()",
        'await requirePermission("requests.approve")',
      ),
      /페이지용이다/,
    ],
    "전체를 try 로 감싼 액션": [
      action(
        `  try {\n    await requireUser();\n${UPDATE}\n  } catch (error) { return { ok: false, message: "x" }; }`,
      ),
      /catch 가 삼킨다/,
    ],
    "바뀐 행을 확인하지 않는 액션": [
      action(UPDATE.replace('.select("id")', "")),
      /바뀐 행을 확인하지 않는다/,
    ],
    "상태 조건 없이 상태를 바꾸는 액션": [
      action(UPDATE.replace('.eq("status", current.data.status)', "")),
      /바꾸기 전의 상태 조건이 없다/,
    ],
    "화면을 갱신하지 않는 액션": [
      action(UPDATE).replace('  revalidatePath("/requests");\n', ""),
      /화면을 갱신하지 않는다/,
    ],
  };
  it("규칙대로 쓴 상태 변경 액션은 통과한다", () => {
    good();
    write("app/(app)/memos/actions.ts", action(UPDATE));
    const result = check();
    assert.equal(result.status, 0, result.stderr);
  });
  it("상태를 바꾸지 않는 수정에는 상태 조건을 요구하지 않는다", () => {
    good();
    write(
      "app/(app)/memos/actions.ts",
      action(
        `  const changed = await supabase.from("memos").update({ body: input.data.body }).eq("id", input.data.id).select("id");`,
      ),
    );
    assert.equal(check().status, 0);
  });
  for (const [title, [content, expected]] of Object.entries(badActions)) {
    it(`${title}을(를) 알린다`, () => {
      good();
      write("app/(app)/memos/actions.ts", content);
      const result = check();
      assert.equal(result.status, 1);
      assert.match(result.stderr, expected);
    });
  }
  const injections = {
    "사용자 글을 HTML 로 넣는 화면": [
      "app/(app)/memos/memo-form.tsx",
      '"use client";\nexport function MemoForm({ body }) { return <div dangerouslySetInnerHTML={{ __html: body }} />; }',
      /dangerouslySetInnerHTML/,
    ],
    "필터 문자열에 값을 끼워 넣는 조회": [
      "app/(app)/memos/queries.ts",
      'import "server-only";\nexport async function search(keyword) { return supabase.from("memos").select("id").or(`title.ilike.%${keyword}%,body.ilike.%${keyword}%`); }',
      /필터 문자열에 값을 끼워 넣는다/,
    ],
    "검색어를 패턴에 그대로 넣는 조회": [
      "app/(app)/memos/queries.ts",
      'import "server-only";\nexport async function search(keyword) { return supabase.from("memos").select("id").ilike("title", `%${keyword}%`); }',
      /toContainsPattern/,
    ],
    "없는 행을 본문으로만 알리는 상세 페이지": [
      "app/(app)/memos/[id]/page.tsx",
      "export default async function Page() { await requireUser(); return <p>찾을 수 없습니다</p>; }",
      /notFound\(\) 를 부르지 않는다/,
    ],
    "밖에서 온 값으로 이동하는 액션": [
      "app/(auth)/login/actions.ts",
      '"use server";\nexport async function login(_previous, formData) { const input = schema.safeParse({}); const next = formData.get("next"); redirect(next); }',
      /밖에서 온 값\(next\)으로 redirect/,
    ],
  };
  for (const [title, [path, content, expected]] of Object.entries(injections)) {
    it(`${title}을(를) 알린다`, () => {
      good();
      write(path, content);
      const result = check();
      assert.equal(result.status, 1);
      assert.match(result.stderr, expected);
    });
  }
  it("값을 인자로 받는 필터와 확인한 경로로의 이동은 통과한다", () => {
    good();
    write(
      "app/(app)/memos/queries.ts",
      'import "server-only";\nexport async function search(keyword) { return supabase.from("memos").select("id").ilike("title", toContainsPattern(keyword)).or("is_pinned.eq.true,is_public.eq.true"); }',
    );
    write(
      "app/(app)/memos/[id]/page.tsx",
      "export default async function Page() { await requireUser(); const memo = null; if (memo === null) notFound(); return null; }",
    );
    write(
      "app/(auth)/login/actions.ts",
      '"use server";\nexport async function login(_previous, formData) { const input = schema.safeParse({}); redirect(safeRedirectPath(formData.get("next"))); }',
    );
    const result = check();
    assert.equal(result.status, 0, result.stderr);
  });
  it("테스트가 없는 규칙 파일을 알린다", () => {
    good();
    rmSync(join(project, "app/(app)/memos/rules.test.ts"));
    assert.match(check().stderr, /rules\.test\.ts 가 없다/);
  });
  it("역슬래시가 든 경로를 알린다", () => {
    good();
    write(
      "app/\\(app\\)/memos/page.tsx",
      "export default function Page() { return null; }",
    );
    assert.match(check().stderr, /역슬래시/);
  });
});

describe("report-rules", () => {
  const RULES = `# 업무 규칙

## 5. 업무 규칙

| 규칙 | 강제 |
|---|---|
| 제출 상태가 아니면 승인·반려할 수 없다 | 서버 액션 |
| 쓰지 않는 품목은 새 신청에서 고를 수 없다 | 서버 액션 |

## 6. 하지 않는 것
`;
  it("테스트가 없는 규칙을 알리고 종료 코드는 0 이다", () => {
    write("docs/rules.md", RULES);
    write(
      "app/(app)/requests/[id]/rules.test.ts",
      'it("제출 상태가 아니면 승인·반려할 수 없다", () => {});',
    );
    const result = run("report-rules.mjs");
    assert.equal(result.status, 0);
    assert.match(
      result.stdout,
      /규칙 2개 가운데 같은 이름의 테스트가 있는 것 1개/,
    );
    assert.match(
      result.stdout,
      /테스트 없음: 쓰지 않는 품목은 새 신청에서 고를 수 없다/,
    );
    assert.doesNotMatch(result.stdout, /테스트 없음: 제출 상태가 아니면/);
  });
  it("규칙 문장을 이름으로 한 describe 묶음도 인정한다", () => {
    write("docs/rules.md", RULES);
    write(
      "app/(app)/requests/[id]/rules.test.ts",
      'describe("제출 상태가 아니면 승인·반려할 수 없다", () => { it("승인 상태면 실패한다", () => {}); });',
    );
    assert.doesNotMatch(
      run("report-rules.mjs").stdout,
      /테스트 없음: 제출 상태가 아니면/,
    );
  });
  it("문서가 없어도 종료 코드는 0 이다", () => {
    assert.equal(run("report-rules.mjs").status, 0);
  });
});

describe("report-scale", () => {
  it("규모가 커도 종료 코드는 0 이고 알림만 낸다", () => {
    migration(
      "20260201000000_many",
      Array.from(
        { length: 25 },
        (_, index) => `create table public.t${index} (id bigint primary key);`,
      ).join("\n"),
    );
    for (let index = 0; index < 40; index += 1)
      write(
        `app/(app)/s${index}/page.tsx`,
        "export default function Page() { return null; }",
      );
    config(["storage", "email", "excel", "db-functions"]);
    const result = run("report-scale.mjs");
    assert.equal(result.status, 0);
    assert.match(result.stdout, /테이블 26개/);
    assert.match(result.stdout, /화면 40개/);
    assert.match(result.stdout, /개발을 멈출 필요는 없다/);
  });
  it("작은 프로젝트에서는 알림이 없다", () => {
    const result = run("report-scale.mjs");
    assert.equal(result.status, 0);
    assert.doesNotMatch(result.stdout, /\[알림\]/);
  });
});

describe("db-push", { skip: process.platform === "win32" }, () => {
  let log = "";
  const push = (args, input, env = {}) =>
    run("db-push.mjs", args, {
      input,
      env: {
        DB_PUSH_TEST: "1",
        SUPABASE_BIN: join(project, "fake-supabase"),
        ...env,
      },
    });
  const calls = () => {
    try {
      return readFileSync(log, "utf8").trim().split("\n");
    } catch {
      return [];
    }
  };

  beforeEach(() => {
    log = join(project, "supabase-calls.log");
    chmodSync(
      write("fake-supabase", `#!/bin/sh\necho "$@" >> "${log}"\nexit 0\n`),
      0o755,
    );
    write(
      "package.json",
      JSON.stringify({
        name: "fixture",
        scripts: { test: 'node -e "process.exit(0)"' },
      }),
    );
    write(
      "supabase/project-refs.json",
      JSON.stringify({ dev: DEV, prod: PROD }),
    );
    mkdirSync(join(project, "scripts"), { recursive: true });
    for (const name of ["check-migrations.mjs", "lib.mjs"])
      writeFileSync(
        join(project, "scripts", name),
        readFileSync(join(SCRIPTS, name)),
      );
  });

  it("터미널이 아니면 실행하지 않는다", () => {
    const result = push([], "y\n", { DB_PUSH_TEST: "" });
    assert.equal(result.status, 1);
    assert.match(result.stderr, /사람이 터미널에서/);
    assert.deepEqual(calls(), []);
  });
  it("개발 DB 에 적용하고 적용한 파일을 기록한다", () => {
    const result = push([], "y\n");
    assert.equal(result.status, 0, result.stderr);
    assert.deepEqual(calls(), [
      `db push --project-ref ${DEV.ref} --dry-run`,
      `db push --project-ref ${DEV.ref} --yes`,
    ]);
    assert.equal(
      readFileSync(join(project, "supabase/.pushed"), "utf8"),
      "20260101000000_rbac.sql\n",
    );
    assert.match(result.stdout, /pnpm db:types/);
  });
  it("확인하지 않으면 적용하지 않는다", () => {
    const result = push([], "n\n");
    assert.equal(result.status, 1);
    assert.deepEqual(calls(), [`db push --project-ref ${DEV.ref} --dry-run`]);
  });
  it("운영은 프로젝트 이름을 입력해야 적용한다", () => {
    assert.equal(push(["--prod"], "y\n").status, 1);
    assert.equal(push(["--prod"], `${DEV.name}\n`).status, 1);
    assert.ok(calls().every((call) => call.endsWith("--dry-run")));

    const result = push(["--prod"], `${PROD.name}\n`);
    assert.equal(result.status, 0, result.stderr);
    assert.equal(calls().at(-1), `db push --project-ref ${PROD.ref} --yes`);
  });
  it("마이그레이션 검사가 실패하면 DB 에 닿지 않는다", () => {
    migration("20260201000000_drop", "drop table public.profiles;");
    const result = push([], "y\n");
    assert.equal(result.status, 1);
    assert.deepEqual(calls(), []);
  });
  it("프로젝트 정보가 없으면 실행하지 않는다", () => {
    write(
      "supabase/project-refs.json",
      JSON.stringify({
        dev: { ref: "", name: "" },
        prod: { ref: "", name: "" },
      }),
    );
    assert.match(push([], "y\n").stderr, /project-refs\.json/);
  });
});

describe("check-app: 경계", () => {
  const check = () => run("check-app.mjs");

  it("출처를 확인하지 않는 Route Handler 를 알린다", () => {
    write(
      "app/api/memos/route.ts",
      "export async function POST(request) { return Response.json({ ok: true }); }",
    );
    const result = check();
    assert.equal(result.status, 1);
    assert.match(result.stderr, /출처를 확인하지 않는다/);
  });
  it("출처를 확인하거나 비밀 값을 확인하는 Route Handler 는 통과한다", () => {
    write(
      "app/api/memos/route.ts",
      'export async function POST(request) { if (!isSameOrigin(request)) return new Response("x", { status: 403 }); }',
    );
    write(
      "app/api/cron/expire/route.ts",
      "export async function GET(request) { const secret = process.env.CRON_SECRET; }",
    );
    write("app/auth/confirm/route.ts", "export async function GET(request) {}");
    const result = check();
    assert.equal(result.status, 0, result.stderr);
  });
  it("확인해 둔 값으로 옮기는 것은 통과한다", () => {
    write(
      "app/(auth)/login/page.tsx",
      "export default async function Login({ searchParams }) { const next = safeRedirectPath((await searchParams).next); redirect(next); }",
    );
    const result = check();
    assert.equal(result.status, 0, result.stderr);
  });
});

describe("check-extensions: 시작 마이그레이션", () => {
  it("시작 마이그레이션의 함수와 트리거는 확장으로 보지 않는다", () => {
    migration(
      "20260101000000_rbac",
      `create function private.log_user_role_change() returns trigger language plpgsql as $$ begin return new; end $$;
       create trigger user_roles_log_change after insert on public.user_roles for each row execute function private.log_user_role_change();`,
    );
    const result = run("check-extensions.mjs");
    assert.equal(result.status, 0, result.stderr);
  });
  it("다른 파일의 트리거는 확장을 켜야 한다", () => {
    migration(
      "20260201000000_guard",
      "create trigger t before update on public.profiles for each row execute function private.guard();",
    );
    assert.match(
      run("check-extensions.mjs").stderr,
      /add-extension db-functions/,
    );
  });
});

describe("문서 검사와 기록", () => {
  const check = (...args) => run("check-docs.mjs", args);
  const git = (...args) =>
    spawnSync("git", args, { cwd: project, encoding: "utf8" });
  const template = (kind) =>
    readFileSync(join(SCRIPTS, "..", "docs", kind, "_template.md"), "utf8");
  const WORK_OPEN = `# 신청 목록 검색

- 날짜: 2026-09-30
- 상태: 진행 중
- 요청: 신청 목록에 검색을 넣어 줘
- 근거 문서: docs/screens.md 신청 목록

## 계획
- 바꿀 파일: app/(app)/memos/queries.ts

## 결정
없음

## 한 일

## 검증

## 하지 않은 것

## 사람이 할 일

## 다음에 막을 것
`;
  const WORK_DONE = WORK_OPEN.replace("상태: 진행 중", "상태: 완료")
    .replace("## 한 일\n", "## 한 일\n- app/(app)/memos/queries.ts — 검색 조건\n")
    .replace("## 검증\n", "## 검증\n- `pnpm verify`: 통과. 테스트 55건\n")
    .replace("## 하지 않은 것\n", "## 하지 않은 것\n- 품목 이름 검색\n")
    .replace("## 사람이 할 일\n", "## 사람이 할 일\n- [ ] member 계정으로 /memos 에서 검색 확인\n")
    .replace("## 다음에 막을 것\n", "## 다음에 막을 것\n- 검색 패턴을 직접 만들었다 — 검사가 없었다 — check:app 에 더한다\n");
  const DECISION = `# 엑셀 패키지

- 날짜: 2026-09-30
- 상태: 확정
- 정한 사람: 담당자
- 관련 작업: 없음

## 배경
엑셀로 내려받아야 한다.

## 선택지
| 선택지 | 좋은 점 | 나쁜 점 |
|---|---|---|
| exceljs | 서식 | 크다 |

## 결정
exceljs 를 쓴다.

## 영향
- 바뀌는 것: package.json
`;

  beforeEach(() => {
    write("docs/work/_template.md", template("work"));
    write("docs/decisions/_template.md", template("decisions"));
    write("docs/schema.md", "# 데이터\n");
    write("docs/screens.md", "# 화면 목록\n\n| 화면 | 경로 |\n|---|---|\n| 메모 | `/memos` |\n");
    write("app/(app)/memos/page.tsx", "export default function Page() { return null; }");
    git("init", "-q", "-b", "main");
    git("config", "user.email", "test@example.com");
    git("config", "user.name", "test");
    git("add", "-A");
    git("commit", "-q", "-m", "start");
  });

  it("바뀐 것이 없으면 통과한다", () => {
    const result = check();
    assert.equal(result.status, 0, result.stderr);
  });
  it("문서만 바꾸면 작업 기록을 요구하지 않는다", () => {
    write("docs/schema.md", "# 데이터\n\n메모\n");
    assert.equal(check().status, 0);
  });
  it("코드를 바꿨는데 작업 기록이 없으면 막는다", () => {
    write("app/(app)/memos/queries.ts", 'import "server-only";');
    const result = check();
    assert.equal(result.status, 1);
    assert.match(result.stderr, /작업 기록이 없다/);
    assert.match(result.stderr, /pnpm docs:new work/);
  });
  it("진행 중인 작업 기록이 있으면 통과한다", () => {
    write("app/(app)/memos/queries.ts", 'import "server-only";');
    write("docs/work/2026-09-30-신청-목록-검색.md", WORK_OPEN);
    const result = check();
    assert.equal(result.status, 0, result.stderr);
  });
  it("올리기 전에는 끝난 기록이어야 한다", () => {
    write("app/(app)/memos/queries.ts", 'import "server-only";');
    write("docs/work/2026-09-30-신청-목록-검색.md", WORK_OPEN);
    assert.match(check("--final").stderr, /올리기 전에 끝내야 한다/);
    write("docs/work/2026-09-30-신청-목록-검색.md", WORK_DONE);
    const result = check("--final");
    assert.equal(result.status, 0, result.stderr);
  });
  it("양식 그대로인 기록을 막는다", () => {
    write("app/(app)/memos/queries.ts", 'import "server-only";');
    write(
      "docs/work/2026-09-30-신청-목록-검색.md",
      template("work").replace("《제목》", "검색").replace("《날짜》", "2026-09-30"),
    );
    assert.match(check().stderr, /「요청」가 비어 있다/);
  });
  it("끝났다고 적었는데 비어 있는 절과 남은 안내를 막는다", () => {
    write("app/(app)/memos/queries.ts", 'import "server-only";');
    write(
      "docs/work/2026-09-30-신청-목록-검색.md",
      WORK_OPEN.replace("상태: 진행 중", "상태: 완료"),
    );
    const result = check();
    assert.match(result.stderr, /「## 한 일」 절이 비어 있다/);
    assert.match(result.stderr, /pnpm verify 의 결과가 없다/);
  });
  it("절 제목이 빠졌거나 이름·상태가 틀린 기록을 막는다", () => {
    write("app/(app)/memos/queries.ts", 'import "server-only";');
    write(
      "docs/work/검색.md",
      WORK_OPEN.replace("## 하지 않은 것\n", "").replace("진행 중", "작업중"),
    );
    const result = check();
    assert.match(result.stderr, /파일 이름이/);
    assert.match(result.stderr, /「## 하지 않은 것」 절이 없다/);
    assert.match(result.stderr, /상태 값이 「작업중」/);
  });
  it("마이그레이션을 더했으면 schema.md 도 바뀌어야 한다", () => {
    write("docs/work/2026-09-30-신청-목록-검색.md", WORK_OPEN);
    migration("20260201000000_add_memos", "create table public.memos (id uuid primary key);");
    assert.match(check().stderr, /docs\/schema\.md 가 그대로다/);
    write("docs/schema.md", "# 데이터\n\n| memos |\n");
    const result = check();
    assert.equal(result.status, 0, result.stderr);
  });
  it("새 화면의 경로가 화면 목록에 있어야 한다", () => {
    write("docs/work/2026-09-30-신청-목록-검색.md", WORK_OPEN);
    write("app/(app)/memos/[id]/page.tsx", "export default function Page() { return null; }");
    assert.match(check().stderr, /새 화면 \/memos\/\[id\] 가 화면 목록에 없다/);
    write("docs/screens.md", "| 메모 | `/memos` |\n| 메모 상세 | `/memos/[id]` |\n");
    const result = check();
    assert.equal(result.status, 0, result.stderr);
    write("app/health/page.tsx", "export default function Page() { return null; }");
    write("app/(auth)/login/page.tsx", "export default function Page() { return null; }");
    assert.equal(check().status, 0, "기반 화면은 화면 목록을 요구하지 않는다");
  });
  it("패키지를 더했으면 결정 기록이 있어야 한다", () => {
    write("docs/work/2026-09-30-신청-목록-검색.md", WORK_OPEN);
    write(
      "package.json",
      JSON.stringify({ name: "fixture", dependencies: { exceljs: "^4.4.0" } }),
    );
    const result = check();
    assert.match(result.stderr, /패키지를 더했다: exceljs/);
    assert.match(result.stderr, /pnpm docs:new decision/);
    write("docs/decisions/2026-09-30-엑셀-패키지.md", DECISION);
    const after = check();
    assert.equal(after.status, 0, after.stderr);
  });
  it("확장을 켰거나 sensitive-ok 를 적었으면 결정 기록이 있어야 한다", () => {
    write("docs/work/2026-09-30-신청-목록-검색.md", WORK_OPEN);
    write("docs/schema.md", "# 데이터\n\n바뀜\n");
    config(["storage"]);
    migration(
      "20260201000000_add_account",
      "-- sensitive-ok: 급여 이체용. 암호화한 값만 넣기로 사용자가 정했다\nalter table public.profiles add column bank_account bytea;",
    );
    const result = check();
    assert.match(result.stderr, /확장을 켰다: storage/);
    assert.match(result.stderr, /sensitive-ok 가 있다/);
    write("docs/decisions/2026-09-30-확장-storage.md", DECISION.replace("exceljs 를 쓴다.", "방식 파일 .claude/skills/add-extension/recipes/storage.md 를 따른다."));
    const after = check();
    assert.doesNotMatch(after.stderr, /확장 storage 의 결정 기록에/);
    write("docs/decisions/2026-09-30-확장-storage.md", DECISION);
    assert.match(check().stderr, /방식 파일\(.claude\/skills\/add-extension\/recipes\/storage\.md\)이 적혀 있지 않다/);
  });
  it("브랜치에서 커밋한 변경도 본다", () => {
    git("checkout", "-q", "-b", "feat/search");
    write("app/(app)/memos/queries.ts", 'import "server-only";');
    git("add", "-A");
    git("commit", "-q", "-m", "feat");
    assert.match(check().stderr, /작업 기록이 없다/);
    assert.match(check("--base", "main").stderr, /작업 기록이 없다/);
    git("checkout", "-q", "main");
    assert.equal(check().status, 0);
  });
  it("git 저장소가 아니면 알리고 양식만 본다", () => {
    rmSync(join(project, ".git"), { recursive: true, force: true });
    write("app/(app)/memos/queries.ts", 'import "server-only";');
    const result = check();
    assert.equal(result.status, 0, result.stderr);
    assert.match(result.stdout, /git 저장소가 아니어서/);
  });

  it("docs:new 는 오늘 날짜로 기록을 만들고 같은 이름을 다시 만들지 않는다", () => {
    const created = run("new-doc.mjs", ["work", "신청", "목록", "검색"]);
    assert.equal(created.status, 0, created.stderr);
    const path = created.stdout.split("\n")[0];
    assert.match(path, /^docs\/work\/\d{4}-\d{2}-\d{2}-신청-목록-검색\.md$/);
    const text = readFileSync(join(project, path), "utf8");
    assert.match(text, /^# 신청 목록 검색/);
    assert.match(text, /- 날짜: \d{4}-\d{2}-\d{2}/);
    assert.doesNotMatch(text, /이 파일을 고치지 않는다/);
    assert.equal(run("new-doc.mjs", ["work", "신청", "목록", "검색"]).status, 1);
    assert.equal(run("new-doc.mjs", ["decision", "엑셀 패키지"]).status, 0);
    assert.equal(run("new-doc.mjs", ["memo", "x"]).status, 1);
    assert.equal(run("new-doc.mjs", ["work", "!!!"]).status, 1);
  });
  it("report:docs 는 남은 일을 모아 알리고 종료 코드는 0 이다", () => {
    write("docs/work/2026-09-29-지난-작업.md", WORK_DONE);
    write("docs/work/2026-09-30-신청-목록-검색.md", WORK_OPEN);
    write(
      "docs/decisions/2026-09-30-엑셀-패키지.md",
      DECISION.replace("상태: 확정", "상태: 제안"),
    );
    const result = run("report-docs.mjs");
    assert.equal(result.status, 0);
    assert.match(result.stdout, /작업 기록 2건, 결정 기록 1건/);
    assert.match(result.stdout, /끝나지 않은 작업\n- docs\/work\/2026-09-30-신청-목록-검색\.md/);
    assert.match(result.stdout, /member 계정으로 \/memos 에서 검색 확인/);
    assert.match(result.stdout, /정해지지 않은 결정/);
    assert.match(result.stdout, /검색 패턴을 직접 만들었다/);
    assert.doesNotMatch(result.stdout, /_template/);
  });
  it("기록이 없어도 report:docs 는 종료 코드 0 이다", () => {
    const result = run("report-docs.mjs");
    assert.equal(result.status, 0);
    assert.match(result.stdout, /남은 일 없음/);
  });
});
