-- 시작 마이그레이션: 역할·권한(RBAC)과 프로필.
-- Supabase 공식 문서 "Custom Claims & RBAC" 의 구조다. 역할이 로그인 토큰의 user_role 에 들어가고,
-- 정책은 authorize('권한 코드') 로 권한을 확인한다.
-- 첫 pnpm db:push 전에 역할 이름을 정한다. 적용한 뒤에는 이름을 바꾸지 않는다(더하기만 한다).

-- 1) 역할과 권한 코드
create type public.app_role as enum ('member', 'admin');
create type public.app_permission as enum ('users.manage');

comment on type public.app_role is '역할. 새 역할은 alter type … add value 로 더한다';
comment on type public.app_permission is '권한 코드(대상.동작). 코드와 정책은 역할이 아니라 이 값을 검사한다';

-- 2) 테이블
create table public.profiles (
  id          uuid primary key references auth.users on delete cascade,
  full_name   text not null check (char_length(full_name) between 1 and 50),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
comment on table public.profiles is '사용자 프로필. auth.users 와 1:1';

create table public.user_roles (
  id       bigint generated by default as identity primary key,
  user_id  uuid not null references auth.users on delete cascade,
  role     public.app_role not null,
  unique (user_id)
);
comment on table public.user_roles is '사용자별 역할. 행이 없으면 member';

create table public.role_permissions (
  id          bigint generated by default as identity primary key,
  role        public.app_role not null,
  permission  public.app_permission not null,
  unique (role, permission)
);
comment on table public.role_permissions is '역할×권한 표의 원본. docs/permissions.md 와 같아야 한다';

insert into public.role_permissions (role, permission) values
  ('admin', 'users.manage');

-- 3) 로그인 토큰에 역할을 넣는 훅 (대시보드 Authentication › Hooks 에서 켜야 동작한다)
create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
set search_path = ''
as $$
declare
  claims jsonb;
  user_role public.app_role;
begin
  select role into user_role from public.user_roles
  where user_id = (event->>'user_id')::uuid;

  claims := event->'claims';
  claims := jsonb_set(claims, '{user_role}', to_jsonb(coalesce(user_role, 'member'::public.app_role)));
  return jsonb_set(event, '{claims}', claims);
end;
$$;

grant usage on schema public to supabase_auth_admin;
grant execute on function public.custom_access_token_hook to supabase_auth_admin;
revoke execute on function public.custom_access_token_hook from authenticated, anon, public;
grant select on table public.user_roles to supabase_auth_admin;

-- 4) 정책 안에서 쓰는 권한 확인 함수
-- security invoker(기본값)다. 부른 사용자의 권한으로 role_permissions 를 읽는다(모든 로그인 사용자가 읽을 수 있는 표).
-- 공식 예제는 security definer 지만, 노출 스키마(public)의 security definer 함수는 보안 점검(0028·0029)에 걸린다.
create or replace function public.authorize(requested_permission public.app_permission)
returns boolean
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
  user_role public.app_role;
begin
  select coalesce(nullif(auth.jwt() ->> 'user_role', ''), 'member')::public.app_role into user_role;
  return exists (
    select 1 from public.role_permissions
    where role_permissions.permission = requested_permission
      and role_permissions.role = user_role
  );
end;
$$;

revoke execute on function public.authorize from anon, public;
grant execute on function public.authorize to authenticated;

-- 5) RLS 와 권한(grant). 테이블마다 셋을 함께 쓴다: enable row level security, grant, 작업별 정책.
alter table public.profiles         enable row level security;
alter table public.user_roles       enable row level security;
alter table public.role_permissions enable row level security;

grant select, insert, update on table public.profiles to authenticated;
grant select, insert, update, delete on table public.user_roles to authenticated;
grant select on table public.role_permissions to authenticated;

create policy "auth admin reads user roles" on public.user_roles
  for select to supabase_auth_admin using (true);

create policy "role_permissions: read" on public.role_permissions
  for select to authenticated using (true);

create policy "user_roles: read own or manage" on public.user_roles
  for select to authenticated
  using (user_id = (select auth.uid()) or (select public.authorize('users.manage')));
create policy "user_roles: manage insert" on public.user_roles
  for insert to authenticated
  with check ((select public.authorize('users.manage')));
create policy "user_roles: manage update" on public.user_roles
  for update to authenticated
  using ((select public.authorize('users.manage')))
  with check ((select public.authorize('users.manage')));
create policy "user_roles: manage delete" on public.user_roles
  for delete to authenticated
  using ((select public.authorize('users.manage')));

create policy "profiles: read all" on public.profiles
  for select to authenticated using (true);
create policy "profiles: insert own" on public.profiles
  for insert to authenticated
  with check (id = (select auth.uid()));
create policy "profiles: update own or manage" on public.profiles
  for update to authenticated
  using (id = (select auth.uid()) or (select public.authorize('users.manage')))
  with check (id = (select auth.uid()) or (select public.authorize('users.manage')));

-- 6) 역할 변경 이력. 누가 누구의 역할을 언제 어떻게 바꿨는지 남긴다.
-- 개인정보를 다루는 시스템은 접근 권한의 부여·변경·말소 기록을 3년 이상 보관해야 한다
-- (개인정보의 안전성 확보조치 기준 제5조). 화면 코드가 아니라 트리거가 남긴다. API 를 직접 불러도 남는다.
create schema if not exists private;

create table public.user_role_events (
  id              bigint generated by default as identity primary key,
  target_user_id  uuid not null,
  actor_id        uuid,
  action          text not null check (action in ('grant', 'change', 'revoke')),
  old_role        public.app_role,
  new_role        public.app_role,
  created_at      timestamptz not null default now()
);
comment on table public.user_role_events is '역할 변경 이력. 트리거가 남긴다. 고치거나 지우지 않는다. 3년 이상 보관';
comment on column public.user_role_events.actor_id is '바꾼 사람. 대시보드나 SQL 로 바꾸면 null';
create index user_role_events_target_idx on public.user_role_events (target_user_id, created_at desc);

-- 읽기만 준다. 쓰기는 트리거만 한다.
grant select on table public.user_role_events to authenticated;
alter table public.user_role_events enable row level security;
create policy "user_role_events: read by manager" on public.user_role_events
  for select to authenticated
  using ((select public.authorize('users.manage')));

-- 바꾼 사용자에게는 이 테이블에 쓸 권한이 없다. 그래서 만든 사람의 권한으로 도는 함수(security definer)로 쓴다.
-- API 로 부를 수 없게 private 스키마에 둔다.
create function private.log_user_role_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.user_role_events (target_user_id, actor_id, action, old_role, new_role)
  values (
    coalesce(new.user_id, old.user_id),
    (select auth.uid()),
    case tg_op when 'INSERT' then 'grant' when 'UPDATE' then 'change' else 'revoke' end,
    case when tg_op = 'INSERT' then null else old.role end,
    case when tg_op = 'DELETE' then null else new.role end
  );
  return coalesce(new, old);
end;
$$;
revoke execute on function private.log_user_role_change() from public, anon, authenticated;

create trigger user_roles_log_change
  after insert or update or delete on public.user_roles
  for each row execute function private.log_user_role_change();
