-- 비품 신청: 품목, 신청, 이력. 규칙은 docs/rules.md, 권한은 docs/permissions.md.
insert into public.role_permissions (role, permission) values
  ('approver', 'requests.approve'),
  ('admin', 'requests.approve'),
  ('admin', 'items.manage');

create type public.request_status as enum ('submitted', 'approved', 'rejected');

create table public.items (
  id          bigint generated by default as identity primary key,
  name        text not null unique check (char_length(name) between 1 and 50),
  unit        text not null default '개' check (char_length(unit) between 1 and 10),
  unit_price  integer not null default 0 check (unit_price >= 0),
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);
comment on table public.items is '품목. items.manage 권한이 관리한다';
comment on column public.items.unit_price is '예상 단가(원). 승인 판단용';

create table public.requests (
  id             bigint generated by default as identity primary key,
  requester_id   uuid not null references public.profiles (id),
  item_id        bigint not null references public.items (id),
  quantity       integer not null check (quantity between 1 and 999),
  reason         text not null check (char_length(reason) between 1 and 200),
  needed_by      date,
  status         public.request_status not null default 'submitted',
  approver_id    uuid references public.profiles (id),
  approver_note  text check (char_length(approver_note) between 1 and 200),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
comment on table public.requests is '신청. 상태 흐름은 docs/rules.md';
create index requests_requester_idx on public.requests (requester_id, created_at desc);
create index requests_status_idx on public.requests (status, created_at desc);
create index requests_item_idx on public.requests (item_id);

create table public.request_events (
  id           bigint generated by default as identity primary key,
  request_id   bigint not null references public.requests (id),
  actor_id     uuid not null references public.profiles (id),
  from_status  public.request_status,
  to_status    public.request_status not null,
  note         text,
  created_at   timestamptz not null default now()
);
comment on table public.request_events is '상태 변경 이력. 서버 액션이 상태를 바꿀 때 한 줄씩 남긴다';
create index request_events_request_idx on public.request_events (request_id, created_at);

grant select, insert, update on table public.items to authenticated;
grant select, insert, update on table public.requests to authenticated;
grant select, insert on table public.request_events to authenticated;

alter table public.items enable row level security;
alter table public.requests enable row level security;
alter table public.request_events enable row level security;

create policy "items: read" on public.items
  for select to authenticated using (true);
create policy "items: manage insert" on public.items
  for insert to authenticated
  with check ((select public.authorize('items.manage')));
create policy "items: manage update" on public.items
  for update to authenticated
  using ((select public.authorize('items.manage')))
  with check ((select public.authorize('items.manage')));

create policy "requests: read own or approve" on public.requests
  for select to authenticated
  using (requester_id = (select auth.uid()) or (select public.authorize('requests.approve')));
create policy "requests: insert own submitted" on public.requests
  for insert to authenticated
  with check (requester_id = (select auth.uid()) and status = 'submitted');
create policy "requests: update own submitted" on public.requests
  for update to authenticated
  using (requester_id = (select auth.uid()) and status = 'submitted')
  with check (requester_id = (select auth.uid()) and status = 'submitted');
create policy "requests: update by approver" on public.requests
  for update to authenticated
  using ((select public.authorize('requests.approve')))
  with check ((select public.authorize('requests.approve')));

create policy "request_events: read if request visible" on public.request_events
  for select to authenticated
  using (exists (select 1 from public.requests r where r.id = request_id));
create policy "request_events: insert as actor" on public.request_events
  for insert to authenticated
  with check (actor_id = (select auth.uid()));
