-- Supabase 가 프로젝트에 미리 만들어 두는 것 가운데 마이그레이션이 기대는 부분만 흉내 낸다.
-- 테스트 전용이다. 실제 Supabase 가 아니다. 마이그레이션을 통과시키려고 이 파일을 고치지 않는다.
-- 기본 권한(alter default privileges)은 일부러 흉내 내지 않는다. 마이그레이션이 grant 를 빠뜨리면 테스트가 잡아야 한다.
create role anon nologin;
create role authenticated nologin;
create role service_role nologin bypassrls;
create role supabase_auth_admin nologin;

create schema auth;
create table auth.users (
  id                  uuid primary key default gen_random_uuid(),
  email               text unique,
  raw_app_meta_data   jsonb not null default '{}',
  raw_user_meta_data  jsonb not null default '{}',
  created_at          timestamptz not null default now()
);

create function auth.jwt() returns jsonb language sql stable
  as $$ select coalesce(nullif(current_setting('request.jwt.claims', true), ''), '{}')::jsonb $$;
create function auth.uid() returns uuid language sql stable
  as $$ select nullif(auth.jwt() ->> 'sub', '')::uuid $$;
create function auth.role() returns text language sql stable
  as $$ select auth.jwt() ->> 'role' $$;

grant usage on schema auth to anon, authenticated, service_role;
grant execute on all functions in schema auth to anon, authenticated, service_role;
grant usage on schema public to anon, authenticated, service_role;

-- 아래는 확장(.claude/skills/add-extension)을 켰을 때 마이그레이션이 기대는 것들이다.
-- 이름과 열만 맞춘 흉내다. 실제 동작(파일 저장, 예약 실행, 실시간 전송)은 하지 않는다.

-- 확장을 설치하는 스키마. create extension … with schema extensions
create schema extensions;
grant usage on schema extensions to anon, authenticated, service_role;

-- storage: 버킷과 파일 목록. 정책(storage.objects)을 테스트할 수 있다.
create schema storage;
create table storage.buckets (
  id                  text primary key,
  name                text not null unique,
  public              boolean not null default false,
  file_size_limit     bigint,
  allowed_mime_types  text[],
  owner_id            text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create table storage.objects (
  id          uuid primary key default gen_random_uuid(),
  bucket_id   text references storage.buckets (id),
  name        text,
  owner_id    text,
  metadata    jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (bucket_id, name)
);
alter table storage.buckets enable row level security;
alter table storage.objects enable row level security;
create function storage.foldername(name text) returns text[] language sql immutable
  as $$ select (string_to_array(name, '/'))[1 : array_length(string_to_array(name, '/'), 1) - 1] $$;
create function storage.filename(name text) returns text language sql immutable
  as $$ select (string_to_array(name, '/'))[array_length(string_to_array(name, '/'), 1)] $$;
create function storage.extension(name text) returns text language sql immutable
  as $$ select reverse(split_part(reverse(storage.filename(name)), '.', 1)) $$;
grant usage on schema storage to anon, authenticated, service_role;
grant select, insert, update, delete on all tables in schema storage to anon, authenticated, service_role;
grant execute on all functions in schema storage to anon, authenticated, service_role;

-- cron: 예약을 등록만 한다. 실행하지 않는다.
create schema cron;
create table cron.job (
  jobid     bigint generated by default as identity primary key,
  jobname   text unique,
  schedule  text not null,
  command   text not null,
  active    boolean not null default true
);
create table cron.job_run_details (
  runid       bigint generated by default as identity primary key,
  jobid       bigint,
  status      text,
  start_time  timestamptz,
  end_time    timestamptz
);
create function cron.schedule(job_name text, schedule text, command text) returns bigint language sql
  as $$ insert into cron.job (jobname, schedule, command) values (job_name, schedule, command)
        on conflict (jobname) do update set schedule = excluded.schedule, command = excluded.command
        returning jobid $$;
create function cron.unschedule(job_name text) returns boolean language sql
  as $$ delete from cron.job where jobname = job_name returning true $$;

-- realtime: 구독 대상 목록(publication)과 방송 권한 테이블.
create publication supabase_realtime;
create schema realtime;
create table realtime.messages (
  id           uuid primary key default gen_random_uuid(),
  topic        text not null,
  extension    text not null,
  event        text,
  payload      jsonb,
  private      boolean not null default false,
  inserted_at  timestamptz not null default now()
);
alter table realtime.messages enable row level security;
create function realtime.topic() returns text language sql stable
  as $$ select nullif(current_setting('realtime.topic', true), '') $$;
grant usage on schema realtime to anon, authenticated, service_role;
grant select, insert on realtime.messages to anon, authenticated, service_role;
grant execute on all functions in schema realtime to anon, authenticated, service_role;
