-- 확장 5종(storage, multi-org, db-functions, scheduled-jobs, realtime)의 본보기 SQL 이다. DB 테스트(extensions.rls.test.ts)로 확인한 것이다.
-- 그대로 복사하지 않는다. 읽고, 자기 테이블에 맞게 /new-migration 의 절차로 쓴다. 실제로는 확장마다 파일을 나눈다.

-- storage
insert into storage.buckets (id, name, public) values ('attachments', 'attachments', false);
create policy "attachments: insert own folder" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'attachments' and (storage.foldername(name))[1] = (select auth.uid()::text));
create policy "attachments: read own folder" on storage.objects
  for select to authenticated
  using (bucket_id = 'attachments' and (storage.foldername(name))[1] = (select auth.uid()::text));

-- multi-org
create schema if not exists private;
create table public.organizations (id uuid primary key default gen_random_uuid(), name text not null);
create table public.org_members (
  org_id uuid not null references public.organizations(id), user_id uuid not null references auth.users on delete cascade,
  primary key (org_id, user_id));
create index org_members_user_idx on public.org_members (user_id);
create function private.user_org_ids() returns setof uuid
  language sql security definer set search_path = '' stable
  as $$ select org_id from public.org_members where user_id = (select auth.uid()) $$;
revoke execute on function private.user_org_ids() from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.user_org_ids() to authenticated;

create type public.request_status as enum ('submitted', 'approved', 'rejected');
create table public.requests (
  id bigint generated by default as identity primary key,
  org_id uuid not null references public.organizations(id),
  requester_id uuid not null references auth.users,
  status public.request_status not null default 'submitted',
  updated_at timestamptz not null default now());
create index requests_org_idx on public.requests (org_id);
grant select on table public.organizations, public.org_members to authenticated;
grant select, insert, update on table public.requests to authenticated;
alter table public.organizations enable row level security;
alter table public.org_members enable row level security;
alter table public.requests enable row level security;
create policy "organizations: read mine" on public.organizations for select to authenticated
  using (id in (select private.user_org_ids()));
create policy "org_members: read mine" on public.org_members for select to authenticated
  using (org_id in (select private.user_org_ids()));
create policy "requests: read org" on public.requests for select to authenticated
  using (org_id in (select private.user_org_ids()));
create policy "requests: insert own in org" on public.requests for insert to authenticated
  with check (org_id in (select private.user_org_ids()) and requester_id = (select auth.uid()));
create policy "requests: update in org" on public.requests for update to authenticated
  using (org_id in (select private.user_org_ids()))
  with check (org_id in (select private.user_org_ids()));

-- db-functions
create function private.guard_request_status() returns trigger
language plpgsql set search_path = '' as $$
begin
  if old.status = new.status then return new; end if;
  if (old.status, new.status) not in (('submitted', 'approved'), ('submitted', 'rejected')) then
    raise exception '상태를 % 에서 % 로 바꿀 수 없다', old.status, new.status using errcode = 'P0001';
  end if;
  return new;
end;
$$;
revoke execute on function private.guard_request_status() from anon, authenticated, public;
create trigger requests_status_guard before update of status on public.requests
  for each row execute function private.guard_request_status();
create extension if not exists moddatetime with schema extensions;
create trigger requests_set_updated_at before update on public.requests
  for each row execute function extensions.moddatetime(updated_at);

-- scheduled-jobs
select cron.schedule('expire-requests', '0 15 * * *', $$ update public.requests set status = 'rejected' where false $$);

-- realtime
alter publication supabase_realtime add table public.requests;
create policy "requests topic: receive" on realtime.messages for select to authenticated
  using (realtime.messages.extension in ('broadcast') and (select realtime.topic()) = 'requests');
